name: "Java CI with Multi-arch Docker Image"

on:
  push:
    tags:
      - 'v*'

jobs:
  docker:
    name: Running Compile Java Multi-arch Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout enstydy
        uses: actions/checkout@v3
      - name: Get Version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build with Maven
        run: mvn -B package -Dmaven.test.skip=true --file pom.xml
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push enstydy version
        id: docker_build_enstydy_version
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./.github/docker/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/ppc64le,linux/s390x
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/enstydy:${{ steps.get_version.outputs.VERSION }}
      - name: Build and push enstydy latest
        id: docker_build_enstydy_latest
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./.github/docker/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/ppc64le,linux/s390x
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/enstydy:latest
